export const REPO_URL = "https://github.com/buiducnhat/agent-skills.git";
export const REPO_BRANCH = "main";

export interface AgentInfo {
	id: string;
	name: string;
}

export const SUPPORTED_AGENTS: AgentInfo[] = [
	{ id: "adal", name: "AdaL" },
	{ id: "amp", name: "Amp" },
	{ id: "antigravity", name: "Antigravity" },
	{ id: "augment", name: "Augment" },
	{ id: "claude-code", name: "Claude Code" },
	{ id: "cline", name: "Cline" },
	{ id: "codebuddy", name: "CodeBuddy" },
	{ id: "codex", name: "Codex" },
	{ id: "command-code", name: "Command Code" },
	{ id: "continue", name: "Continue" },
	{ id: "cortex", name: "Cortex Code" },
	{ id: "crush", name: "Crush" },
	{ id: "cursor", name: "Cursor" },
	{ id: "droid", name: "Droid" },
	{ id: "gemini-cli", name: "Gemini CLI" },
	{ id: "github-copilot", name: "GitHub Copilot" },
	{ id: "goose", name: "Goose" },
	{ id: "iflow-cli", name: "iFlow CLI" },
	{ id: "junie", name: "Junie" },
	{ id: "kilo", name: "Kilo Code" },
	{ id: "kimi-cli", name: "Kimi Code CLI" },
	{ id: "kiro-cli", name: "Kiro CLI" },
	{ id: "kode", name: "Kode" },
	{ id: "mcpjam", name: "MCPJam" },
	{ id: "mistral-vibe", name: "Mistral Vibe" },
	{ id: "mux", name: "Mux" },
	{ id: "neovate", name: "Neovate" },
	{ id: "openclaw", name: "OpenClaw" },
	{ id: "opencode", name: "OpenCode" },
	{ id: "openhands", name: "OpenHands" },
	{ id: "pi", name: "Pi" },
	{ id: "pochi", name: "Pochi" },
	{ id: "qoder", name: "Qoder" },
	{ id: "qwen-code", name: "Qwen Code" },
	{ id: "replit", name: "Replit" },
	{ id: "roo", name: "Roo Code" },
	{ id: "trae", name: "Trae" },
	{ id: "trae-cn", name: "Trae CN" },
	{ id: "windsurf", name: "Windsurf" },
	{ id: "zencoder", name: "Zencoder" },
];

// Maps the skills directory prefix (e.g., ".claude") to the skills CLI canonical agent ID.
// Used for filesystem-based auto-detection of installed agents.
export const AGENT_SKILLS_DIRS: Record<string, string> = {
	".adal": "adal",
	".agent": "antigravity",
	".agents": "amp",
	".augment": "augment",
	".claude": "claude-code",
	".codebuddy": "codebuddy",
	".commandcode": "command-code",
	".continue": "continue",
	".cortex": "cortex",
	".crush": "crush",
	".cursor": "cursor",
	".factory": "droid",
	".gemini": "gemini-cli",
	".goose": "goose",
	".iflow": "iflow-cli",
	".junie": "junie",
	".kilocode": "kilo",
	".kiro": "kiro-cli",
	".kode": "kode",
	".mcpjam": "mcpjam",
	".mux": "mux",
	".neovate": "neovate",
	".openhands": "openhands",
	".pi": "pi",
	".pochi": "pochi",
	".qoder": "qoder",
	".qwen": "qwen-code",
	".roo": "roo",
	".trae": "trae",
	".vibe": "mistral-vibe",
	".windsurf": "windsurf",
	".zencoder": "zencoder",
	skills: "openclaw",
};

export const AGENT_RULES_MAP: Record<string, string> = {
	// AGENTS.md group
	"github-copilot": "AGENTS.md",
	codex: "AGENTS.md",
	pi: "AGENTS.md",
	cursor: "AGENTS.md",
	amp: "AGENTS.md",
	"gemini-cli": "AGENTS.md",
	kilo: "AGENTS.md",
	opencode: "AGENTS.md",
	"qwen-code": "AGENTS.md",
	roo: "AGENTS.md",
	droid: "AGENTS.md",
	"mistral-vibe": "AGENTS.md",
	aider: "AGENTS.md",
	windsurf: "AGENTS.md",
	replit: "AGENTS.md",
	adal: "AGENTS.md",
	codebuddy: "AGENTS.md",
	"command-code": "AGENTS.md",
	continue: "AGENTS.md",
	cortex: "AGENTS.md",
	"iflow-cli": "AGENTS.md",
	"kimi-cli": "AGENTS.md",
	kode: "AGENTS.md",
	mcpjam: "AGENTS.md",
	mux: "AGENTS.md",
	neovate: "AGENTS.md",
	openclaw: "AGENTS.md",
	pochi: "AGENTS.md",
	qoder: "AGENTS.md",
	"trae-cn": "AGENTS.md",
	zencoder: "AGENTS.md",

	// Unique rules files
	"claude-code": "CLAUDE.md",
	cline: ".clinerules",
	crush: "CRUSH.md",

	// Nested paths
	antigravity: ".agent/rules/ruler.md",
	"amazon-q": ".amazonq/rules/ruler_q_rules.md",
	"firebase-studio": ".idx/airules.md",
	openhands: ".openhands/microagents/repo.md",
	junie: ".junie/guidelines.md",
	augment: ".augment/rules/ruler_augment_instructions.md",
	trae: ".trae/rules/project_rules.md",
	"kiro-cli": ".kiro/steering/ruler_kiro_instructions.md",
	"jetbrains-ai": ".aiassistant/rules/AGENTS.md",
	goose: ".goosehints",
};

export const RULES_MARKER_START = "<!-- BEGIN agent-skills rules -->";
export const RULES_MARKER_END = "<!-- END agent-skills rules -->";
